[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
axum = { version = "0.8", features = ["macros"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["cors"] }
chrono = {version = "0.4.44", features = ["serde"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls", "time", "json", "chrono"] }
thiserror = "2.0.18"
async-trait = "0.1.89"
dotenv = "0.15.0"
lox-space = "0.1.0-alpha.48"
