[package]
name = "adapters"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { path = "../application" }
domain = { path = "../domain" }
ports = { path = "../ports" }

serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true }
lox-space = { workspace = true }
